### ISSUE TITLE
Suggestion: Resolve Kernel Compilation Errors on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by Daeh0f** [awslabs/snapchange#13]
Hi Team,

I've been using your project and I must say, it's amazing. However, I've noticed a minor issue when running on Ubuntu 22.04.2 that could use some attention.

During my use, I've encountered kernel compilation errors that seem to be tied to the `binutils` version. Luckily, I've found a workaround: using kernel version 5.19 seems to resolve the problem.

So, I'm thinking it could be useful to implement this fix into the project. If you're open to it, I'm ready to prepare a PR for this change.

Here's a brief overview of what the fix would look like:
```
-  # Use kernel v5.4
-  ./init.sh --kernel-version v5.4
-
+  if [ "$( cat /etc/os-release | grep ^VERSION= | cut -d'"' -f2)" = "22.04.2 LTS (Jammy Jellyfish)" ]; 
+  then 
+    # Use kernel v5.19 
+    ./init.sh --kernel-version v5.19
+  else 
+    # Use kernel v5.4
+    ./init.sh --kernel-version v5.4
+  fi
```
Let me know what you think about small fixes like that, and if there are any further steps I should take.

**Comment by corydu** [comment]
Thank you for the kind words and thanks for checking out the project.

That is a great suggestion. The reason the current setup uses Ubuntu 20.04 is precisely this reason, so it's fun to hear you are running into the same. The `v5.4` kernel version is only there for the 4th example demonstrating a known bug in the Linux kernel, but defaulting to something more recent is a good idea.

I'll run the examples through `v5.19` (minus example 4 since that needs `v5.4`) and confirm everything works great with it. If so, we'll push up that change. so things are a bit smoother.

I'll leave this open in the meantime.

**Comment by corydu** [comment]
Great! We can default to using kernel `v5.19` and special case the 4th example to use `v5.4`. Thanks for your help!
